# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dd37570853eb28263a880f94cb408f471c3cff6002cdb43a7a92b4c0a4ca39ffd5eb5968fe90014ee7b342b7e6bb558e6e7e809cc65d7c07169eebd37c39336

test:
  secret_key_base: f7f1da20697af73db12839d1ebd1f8f41d35e53aa7139b6128aff61e5bf93854da9ca92dbb61b2bedaf13ce2f8f093a85fe27d6d0244f89c5b0c44d3cd3d31fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
